name: RookieSkills
version: '1.0-SNAPSHOT'
main: com.cuzz.rookieskills.RookieSkills
api-version: '1.20'
depend:
  - MythicLib
  - MythicMobs
commands:
  rsk:
    description: cuzz
    permission: cuzz